version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 780522923809.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t pythonapp:latest .
      - docker tag pythonapp:latest 780522923809.dkr.ecr.us-east-1.amazonaws.com/pythonapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780522923809.dkr.ecr.us-east-1.amazonaws.com/pythonapp:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"pythonapp","imageUri":"780522923809.dkr.ecr.us-east-1.amazonaws.com/pythonapp:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"780522923809.dkr.ecr.us-east-1.amazonaws.com/pythonapp:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
    - Dockerfile
    - Dockerrun.aws.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json